services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    EzSystems\EzRecommendationClient\Event\:
        resource: '../../../../src/lib/Event/*'

    EzSystems\EzRecommendationClient\Event\Listener\LoginListener:
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, priority: 255 }
            - { name: monolog.logger, channel: ezrecommendation }

    EzSystems\EzRecommendationClient\Event\Listener\SessionBackupListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
            - { name: monolog.logger, channel: ezrecommendation }

    EzSystems\EzRecommendationClient\Event\Subscriber\RecommendationEventSubscriber:
        tags:
            - { name: kernel.event_subscriber, event: recommendation.response }

    EzSystems\EzRecommendationClient\Event\Subscriber\RecommendationRandomContentEventSubscriber:
        tags:
            - { name: kernel.event_subscriber, event: recommendation.response }

    EzSystems\EzRecommendationClient\Event\Subscriber\UserAPIEventSubscriber:
        tags:
            - { name: kernel.event_subscriber, event: recommendation.update_user }
            - { name: kernel.event_subscriber, event: recommendation.fetch_user }
